name: Test
on: [push]
jobs:
  tests:
    defaults:
      run:
        working-directory: ./packages/array-to-string
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: ./packages/array-to-string
      - run: npm run build
        working-directory: ./packages/array-to-string
      - run: npx jest
        working-directory: ./packages/array-to-string
  coverage:
    defaults:
      run:
        working-directory: ./packages/array-to-string
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build
      - run: npx jest --coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./packages/array-to-string/coverage/lcov.info
